version: 2.1

jobs:
  say-hello:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"

  playwright-e2e:
    docker:
      - image: mcr.microsoft.com/playwright:v1.44.0-jammy
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm ci
      - run:
          name: Install Playwright Browsers
          command: npx playwright install --with-deps
      - run:
          name: Run Playwright tests
          command: npx playwright test
      - store_artifacts:
          path: test-results
          destination: playwright-test-results
      - store_artifacts:
          path: playwright-report
          destination: playwright-report

workflows:
  say-hello-workflow:
    jobs:
      - say-hello
      - playwright-e2e
